#!/usr/bin/env python
# The purpose of this node is to allow you to use the turtlesim node
# instead of a real robot while refining your trajectory

import rospy
from turtlesim.msg import Pose
from nav_msgs.msg import Odometry

def sub_callback():
    '''This is the callback function for the Pose subscriber'''
    something = 0

def pub_callback():
    '''This is the callback function for the Odometry publisher'''
    something = 0

if __name__ == '__main__':
    rospy.init_node('simodom')

    sub1 = rospy.Subscriber("turtle1/pose", Pose, sub_callback)

    pub1 = rospy.Publisher("odom", Odometry, pub_callback)

    # Spin() simply keeps python from exiting until this node is stopped
    rospy.spin()